name: Niffler pytest

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
env:
  BASE_URL: $BASE_URL
  TOKEN: ${{ secrets.TOKEN }}
  BASE_AUTH_URL: $BASE_AUTH_URL
  API_BASE_URL: $API_BASE_URL
  TEST_LOGIN: $TEST_LOGIN
  TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
  DB_URL: $DB_URL
  USER_DB_URL: $USER_DB_URL
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  SERVER_NAME: $SERVER_NAME
  SOAP_ADDRESS: $SOAP_ADDRESS
  
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_SHA }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r tests/requirements.txt

  ui_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Run UI tests
        run: pytest tests/ui --alluredir=allure-results
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-ui
          path: allure-results

  api_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r tests/requirements.txt
      - name: Run API tests (parallel)
        run: pytest -n auto tests/test_api_with_db.py --alluredir=allure-results

  soap_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Run SOAP tests
        run: pytest -n auto tests/test_soap.py --alluredir=allure-results
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-soap
          path: allure-results

  kafka_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Run Kafka tests
        run: pytest tests/tes_kafka.py --alluredir=allure-results
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-kafka
          path: allure-results
