name: Niffler pytest

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
env:
  BASE_URL: http://frontend.niffler.dc/
  TOKEN: ${{ secrets.TOKEN }}
  BASE_AUTH_URL: http://auth.niffler.dc:9000/
  API_BASE_URL: http://gateway.niffler.dc:8090/api/
  TEST_LOGIN: asd
  TEST_PASSWORD: asd
  DB_URL: postgresql://postgres:secret@localhost:5432/niffler-spend
  USER_DB_URL: postgresql://postgres:secret@localhost:5432/niffler-userdata
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  SERVER_NAME: localhost
  SOAP_ADDRESS: http://localhost:8089/ws
  
jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build backends
        run: |
          bash docker-compose-dev.sh

      - name: Edit hosts file
        run: |
          echo -e "127.0.0.1\tlocalhost\n127.0.0.1\tfrontend.niffler.dc\n127.0.0.1\tauth.niffler.dc\n127.0.0.1\tgateway.niffler.dc\n127.0.0.1\tkafka" | sudo tee -a /etc/hosts
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_SHA }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r tests/requirements.txt
        
      - name: Run api tests
        if: always()
        run: pytest -n 4 -s -v tests/test_api_with_db.py --alluredir=./allure-results --dist=loadscope -m "not serial"
        continue-on-error: true

      - name: Run kafka tests
        if: always()
        run: pytest -s -v tests/test_kafka.py --alluredir=./allure-results
        
      - name: Run SOAP tests
        if: always()
        run: pytest -s -v tests/test_soap.py --alluredir=./allure-results

      - name: Run UI tests
        if: always()
        run: pytest -s -v tests/test_auth.py tests/test_main.py tests/test_profile.py --alluredir=./allure-results
        continue-on-error: true

      - name: Upload Allure Report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  generate-report:
    name: Generate & Publish Allure Report
    needs: build-and-run-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: tests/allure-history
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev
          allure --version
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-resultss

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
